//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proiect_mds.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jocuri
    {
        public int Id { get; set; }
        public string Nume { get; set; }
        public double Rating { get; set; }
        public int Nr_voturi { get; set; }
        public int Nr_accesari { get; set; }
    }
}
