//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proiect_mds.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserID { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public Nullable<int> Spanzurat { get; set; }
        public Nullable<int> Memo { get; set; }
        public Nullable<int> Ursi { get; set; }
        public Nullable<int> Flap { get; set; }
        public Nullable<int> Invadez { get; set; }
        public Nullable<int> Snek { get; set; }
    }
}
